<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="11" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="557571" started-at="2022-10-29T10:34:11Z" finished-at="2022-10-29T10:43:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="557571" started-at="2022-10-29T10:34:11Z" finished-at="2022-10-29T10:43:29Z">
      <class name="com.ncd.tests.NCD">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.ncd.tests.NCD@43ee72e6]" name="beforeTest" is-config="true" duration-ms="13291" started-at="2022-10-29T10:34:11Z" finished-at="2022-10-29T10:34:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="loginTitleTest()[pri:1, instance:com.ncd.tests.NCD@43ee72e6]" name="loginTitleTest" duration-ms="2770" started-at="2022-10-29T10:34:25Z" finished-at="2022-10-29T10:34:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTitleTest -->
        <test-method status="PASS" signature="loginTestBuyer()[pri:2, instance:com.ncd.tests.NCD@43ee72e6]" name="loginTestBuyer" duration-ms="20527" started-at="2022-10-29T10:34:28Z" finished-at="2022-10-29T10:34:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestBuyer -->
        <test-method status="PASS" signature="autionMarket()[pri:3, instance:com.ncd.tests.NCD@43ee72e6]" name="autionMarket" duration-ms="38111" started-at="2022-10-29T10:34:48Z" finished-at="2022-10-29T10:35:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- autionMarket -->
        <test-method status="PASS" signature="checkStatusBuyer()[pri:4, instance:com.ncd.tests.NCD@43ee72e6]" name="checkStatusBuyer" duration-ms="395325" started-at="2022-10-29T10:35:26Z" finished-at="2022-10-29T10:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusBuyer -->
        <test-method status="PASS" signature="checkNotificationBuyer()[pri:5, instance:com.ncd.tests.NCD@43ee72e6]" name="checkNotificationBuyer" duration-ms="3176" started-at="2022-10-29T10:42:02Z" finished-at="2022-10-29T10:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkNotificationBuyer -->
        <test-method status="PASS" signature="loginTestSeller()[pri:6, instance:com.ncd.tests.NCD@43ee72e6]" name="loginTestSeller" duration-ms="18562" started-at="2022-10-29T10:42:05Z" finished-at="2022-10-29T10:42:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestSeller -->
        <test-method status="PASS" signature="doBookmark()[pri:7, instance:com.ncd.tests.NCD@43ee72e6]" name="doBookmark" duration-ms="45595" started-at="2022-10-29T10:42:23Z" finished-at="2022-10-29T10:43:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBookmark -->
        <test-method status="PASS" signature="checkNotificationSeller()[pri:8, instance:com.ncd.tests.NCD@43ee72e6]" name="checkNotificationSeller" duration-ms="1826" started-at="2022-10-29T10:43:09Z" finished-at="2022-10-29T10:43:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkNotificationSeller -->
        <test-method status="PASS" signature="checkStatusSeller()[pri:9, instance:com.ncd.tests.NCD@43ee72e6]" name="checkStatusSeller" duration-ms="6028" started-at="2022-10-29T10:43:11Z" finished-at="2022-10-29T10:43:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusSeller -->
        <test-method status="FAIL" signature="checkTradeBook()[pri:10, instance:com.ncd.tests.NCD@43ee72e6]" name="checkTradeBook" duration-ms="1328" started-at="2022-10-29T10:43:17Z" finished-at="2022-10-29T10:43:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.ncd.tests.NCD.checkTradeBook(NCD.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTradeBook -->
        <test-method status="FAIL" signature="checkMarginBlock()[pri:11, instance:com.ncd.tests.NCD@43ee72e6]" name="checkMarginBlock" duration-ms="3796" started-at="2022-10-29T10:43:18Z" finished-at="2022-10-29T10:43:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.ncd.tests.NCD.checkMarginBlock(NCD.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkMarginBlock -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.ncd.tests.NCD@43ee72e6]" name="afterTest" is-config="true" duration-ms="7010" started-at="2022-10-29T10:43:22Z" finished-at="2022-10-29T10:43:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.ncd.tests.NCD -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
